# Generated by Django 3.2.2 on 2021-06-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_rename_transaction_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='stock_name',
            field=models.CharField(choices=[('TSLA', 'TESLA'), ('BMW.DE', 'Bayerische Motoren Werke Aktiengesellschaft')], max_length=7),
        ),
    ]
